services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
    networks:
      - elsa-network
    healthcheck:
      test: ["CMD", "mongosh", "--username", "admin", "--password", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  elsa-studio:
    image: elsaworkflows/elsa-studio-v3:latest
    environment:
      - HTTP_PORTS=8080
      - ELSASERVER__URL=http://localhost:5158/elsa/api
    ports:
      - "6002:8080"
    networks:
      - elsa-network

volumes:
  mongodb_data:

networks:
  elsa-network:
    driver: bridge
