namespace Elsa.Workflow.Application.Contracts.ServiceBus;

/// <summary>
/// Outbound Service Bus message that instructs a substore to begin pick preparation.
/// Published once per substore group by <see cref="Activities.ManagePrepareActivity"/>.
/// </summary>
public sealed record PrepareSubstoreCommand(
    /// <summary>
    /// Stable correlation ID generated by the workflow. Used in <see cref="PrepareReportDto"/>
    /// to correlate incoming reports back to the right workflow bookmark.
    /// </summary>
    string PrepareCommandId,
    string FulfilmentOrderId,
    string SubStoreId,
    IReadOnlyList<PrepareLineDto> Lines);

public sealed record PrepareLineDto(
    int     OrderLineNo,
    string  ArticleId,
    decimal AllocatedQuantity);
